/*

   Footsteps handler

*/

/* Include Files */
#include "define.h"
#include "command.h"

#include "sfall/main.h"

/* Standard Script Procedures */
procedure start;
procedure map_enter_p_proc;

procedure MoveCost_handler;
procedure create_prints;
procedure footsteps(variable step_crit);

#define FID_FOOT_1         (33556338)
#define FID_FOOT_2         (33556339)

variable last_step := 0, new_step := 0, step_fid;
variable critter_List, critter;

procedure start begin
   if (game_loaded) then begin
      set_global_script_type(0);
      set_global_script_repeat(1);

      register_hook_proc(HOOK_MOVECOST, MoveCost_handler);
   end

   call create_prints;
end

procedure map_enter_p_proc begin
   //critter_List := list_as_array(LIST_CRITTERS);
end

// Creates footsteps while in combat mode
procedure MoveCost_handler begin
   variable
      critter := get_sfall_arg;

   call footsteps(critter);
end

procedure create_prints begin
   if not(combat_is_initialized) then begin
      /*foreach (critter in list_as_array(critter_List)) begin
         call footsteps(critter);
      end*/

      call footsteps(dude_obj);
   end
end

procedure footsteps(variable step_crit) begin
   new_step := tile_num(step_crit);
   if (last_step != new_step) then begin
      last_step := new_step;

      //debug("get_tile_fid: " + get_tile_fid(dude_tile));
      if (get_tile_fid(tile_num(step_crit)) >= 191 and get_tile_fid(tile_num(step_crit)) <= 198)
         or ((get_tile_fid(tile_num(step_crit)) >= 173) and (get_tile_fid(tile_num(step_crit)) <= 175))
         or (get_tile_fid(tile_num(step_crit)) == 203)
         or ((get_tile_fid(tile_num(step_crit)) >= 205) and (get_tile_fid(tile_num(step_crit)) <= 206))
         or (get_tile_fid(tile_num(step_crit)) == 208)
         or (get_tile_fid(tile_num(step_crit)) == 211)
         or (get_tile_fid(tile_num(step_crit)) == 214)

      then begin
         set_global_var(2000, global_var(2000) + 1);
         Scenery_Creation := create_object_sid(33554866, new_step, elevation(step_crit), SCRIPT_TEST);

         if (step_fid == 0) then begin
            step_fid := 1;
            art_change_fid_num(Scenery_Creation, FID_FOOT_1);
         end
         else begin
            step_fid := 0;
            art_change_fid_num(Scenery_Creation, FID_FOOT_2);
         end
         obj_rotate(Scenery_Creation, get_cur_rot(step_crit));
      end
   end
end

