#
# This file exists so that custom responses can be added to special NPCs without having to edit their actual dialog file.
# That means, the main NPC dialog file doesn't need to be synchronized between multiple languages - only this file.
# NOTE: Responses will not play any sound! If you want sound, the actual NPC dialog needs to be edited.
#

# Generic "My Name"
{100}{}{That is my name.}
{101}{}{You are talking to me.}
{102}{}{Why do you ask silly questions? I am that person.}

# Generic "Don't know"
{103}{}{I don't know anything about that.}
{104}{}{Sorry. No clue.}
{105}{}{Never heard of it.}

#
# Arroyo Elder
#
{150}{}{Why are you still here?}

{200}{}{Temple|Trials}
{201}{}{Geck}
{202}{}{Vault}
{203}{}{Vic|Klamath}
{204}{}{Elder}

{300}{aeld6}{You survived. The Chosen One cannot be weak or we are all doomed. Are you prepared for your quest?}
{301}{aeld10}{It is a holy artifact - the Garden of Eden Creation Kit. The disks promise it will make our lands green and our village prosperous. It will save us. More, I do not know.}
{302}{aeld12}{The holy Thirteen? I can not help you. Only the Vault Dweller knew. His tales have the sound of a perilous journey.}
{303}{aeld16}{Find Vic in Klamath. We are counting on you.}
{304}{}{That is me.}

#
# Arroyo Mynoc
#
{400}{}{Trader|Traders|Merchant|Merchants}
{401}{}{Vic}

{500}{}{Ah yes, the people from Klamath. They trade with us occasionally. Not so much anymore lately, though.}
{501}{}{I don't remember his name, but there was this one merchant who was old and very loud. Haven't seen him in a while now. I wonder if anything happened?}

#
# Arroyo Nagor
#
{600}{}{Smoke}
{700}{}{Smoke is my dog! Have you seen him somewhere?}

#
# Arroyo Lucas/Fist
#
{800}{}{Fist}
{900}{}{You are talking to me.}