{1}{}{Ask about what?}
{2}{}{Done}
{3}{}{Cancel}

##########################
#    "TELL ME ABOUT"     #
#      "my name"         #
#      (970-979)         #
##########################
{970}{}{That is my name.}
{971}{}{You are talking to me.}
{972}{}{Why do you ask silly questions? I am that person.}

##########################
#    "TELL ME ABOUT"     #
#     "don't know"       #
#      (980-999)         #
##########################
{980}{}{I don't know anything about that.}
{981}{}{Sorry. No clue.}
{982}{}{Never heard of it.}

{997}{}{You are too lowly to question me.}
{998}{}{None of your business.}
{999}{}{That is not your concern.}

#
# MAP_ARROYO_
# The Arroyo Tell-Me-Abouts
#
{1000}{}{Elder|Mother}
{1001}{}{Founder}
{1002}{}{Vault Dweller|Dweller|Vince}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Chosen One}
{1007}{}{Shaman|Hakunin}
{1008}{}{Healing Powder}
{1009}{}{Bridge}
{1010}{}{Mynoc}
{1011}{}{Villager|Warrior}
{1012}{}{Healing|Medic|Doctor|Powder}
{1013}{}{Nagor|Smoke}
{1014}{}{Morlis}
{1015}{}{Lucas|Fist}
{1016}{}{Monument}
{1017}{}{Trader|Traders|Merchant|Merchants}
{1018}{}{Geck|Artifact}
{1019}{}{Hunting|Grounds}
{1020}{}{Temple|Trials}

{1100}{}{The Elder is your mother and our leader.}
{1101}{}{Our great ancestor who gave us knowledge.}
{1102}{}{The first to fight and win over chaos.}
{1103}{}{That would be our beautiful village.}
{1104}{}{That's a trading outpost a few days east of here.}
{1105}{}{The Vault is heaven.}
{1106}{}{You are the Chosen One.}
{1107}{}{He heals us with his herbs and magic. He is in the north part of our village.}
{1108}{}{It is a magic powder which will heal you, but will make you sleepy.}
{1109}{}{The Great Bridge exits our village in the south.}
{1110}{}{He guards the bridge leading into our village.}
{1111}{}{We are all people of the village.}
{1112}{}{Hakunin surely can help you if you are hurt.}
{1113}{}{Nagor and his dog Smoke are inseparable.}
{1114}{}{Better not speak of the devil.}
{1115}{}{He is the chief warrior of our tribe. I think he is somewhere near the monument of the Vault Dweller.}
{1116}{}{It is to honor the Vault Dweller, but I know not much about it.}
{1117}{}{They are coming from the south east. I don't know much else about them.}
{1118}{}{The GECK is a holy artifact. We need it to safe our village and make the land green and propserous again!}
{1119}{}{The hunting grounds are to the west, sure you remember?}
{1120}{}{They say the temple contained artifacts of the past a long time ago.}

#
# MAP_DEN_
#
{2000}{}{Den}
{2001}{}{Slave|Slaves|Slavers|Slaver|Guild}
{2002}{}{Klamath}
{2003}{}{Metzger}

{2100}{}{You are in the Den. Need drugs or a slave? Here you'll get it.}
{2101}{}{You'll find the Slaver's Guild in the Business District at the east side.}
{2102}{}{A small town to the north west of here.}
{2103}{}{He leads the Slaver's Guild.}

#
# MAP_DEN_BUSINESS
#
{2200}{}{Den}
{2201}{}{Slave|Slaves|Slavers|Slaver|Guild}
{2202}{}{Klamath}
{2203}{}{Metzger}

{2300}{}{You are in the Den. Need drugs or a slave? Here you'll get it.}
{2301}{}{The Slavers Guild is here, right around the corner.}
{2302}{}{A small town to the north west of here.}
{2303}{}{He leads the Slaver's Guild.}

#
# MAP_KLAMATH_
#
{3400}{}{Klamath}
{3401}{}{Den}
{3402}{}{Slave|Slaves|Slavers|Slaver|Guild}

{3500}{}{You are in Klamath!}
{3501}{}{The Den is a shithole to the south east of here.}
{3502}{}{There is a Slaver's Guild in the Den, just a few days south east of here. I'd stay away if I were you.}

