/*

   Footprint scenery object

*/

#include "define.h"
#include "command.h"

procedure start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;

#define settings_path      "mods\\footprints\\footprints.ini"

variable iniVal;

procedure start begin
   // TODO: Improve this shit
   iniVal := get_ini_setting(settings_path + "|" + "main" + "|" + "alive_time");

   add_timer_event(self_obj, game_ticks(iniVal), 0);
end

procedure look_at_p_proc begin
   script_overrides;
end

procedure description_p_proc begin
   script_overrides;
end

procedure map_enter_p_proc begin
   destroy_object(self_obj);
end

procedure timed_event_p_proc begin
   destroy_object(self_obj);
end
